package memory

import (
	"strings"
	"testing"
	"unicode/utf8"
)

// TestDeriveTitle pins the boundary rules a title is derived under. Every
// expected value is a literal read off the rule, not generated by the
// implementation; the abbreviation cases below each produce a wrong,
// obviously-broken title under a naive first-period split.
func TestDeriveTitle(t *testing.T) {
	tests := []struct {
		name string
		body string
		want string
	}{
		{
			name: "first sentence ends at the period",
			body: "A Vue computed caches its first result. It depends on Date.now().",
			want: "A Vue computed caches its first result.",
		},
		{
			name: "period opening a token is not a sentence end",
			body: "12 .beads stores migrate cleanly. The rest do not.",
			want: "12 .beads stores migrate cleanly.",
		},
		{
			name: "path dot is not a sentence end",
			body: "The path ~/.beads holds stores. It is local.",
			want: "The path ~/.beads holds stores.",
		},
		{
			name: "package selector is not a sentence end",
			body: "Use time.RFC3339Nano for stamps. It is not lexical.",
			want: "Use time.RFC3339Nano for stamps.",
		},
		{
			name: "method call is not a sentence end",
			body: "Date.now() returns millis. Do not sort on it.",
			want: "Date.now() returns millis.",
		},
		{
			name: "version digits are not a sentence end",
			body: "Version v0.15.0 shipped. It changed parsing.",
			want: "Version v0.15.0 shipped.",
		},
		{
			name: "abbreviation followed by lowercase prose is not an end",
			body: "It is e.g. a trap. Really.",
			want: "It is e.g. a trap.",
		},
		{
			name: "call followed by lowercase prose is not an end",
			body: "Wait(). output continues. It does.",
			want: "Wait(). output continues.",
		},
		{
			name: "leading machine header line is excluded",
			body: "@type=semantic:lesson @created=2026-08-14 @salience=4 @refs=br-sht,br-pep\n" +
				"lesson: The dominant defect. It cannot fail.",
			want: "lesson: The dominant defect.",
		},
		{
			name: "short body with no sentence end is used whole",
			body: "A durable note",
			want: "A durable note",
		},
		{
			name: "multibyte rune before the period is kept whole",
			body: "The bug was in the emoji 😀. It crashed.",
			want: "The bug was in the emoji 😀.",
		},
		{
			name: "empty body yields an empty title",
			body: "",
			want: "",
		},
		{
			name: "whitespace-only body yields an empty title",
			body: "   \n\t  ",
			want: "",
		},
		{
			name: "first sentence longer than the limit truncates with ellipsis",
			body: "This sentence keeps rambling on for well over one hundred and twenty runes without a single period anywhere in sight so that the truncation path is the only one left to exercise. Next.",
			want: "This sentence keeps rambling on for well over one hundred and twenty runes without a single period anywhere in " +
				"sight…",
		},
		{
			name: "header with no body returns the header",
			body: "@type=semantic:lesson @salience=3",
			want: "@type=semantic:lesson @salience=3",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := DeriveTitle(tt.body); got != tt.want {
				t.Errorf("DeriveTitle(%q) = %q, want %q", tt.body, got, tt.want)
			}
		})
	}
}

// TestDeriveTitleNeverExceedsMax is the property every title must satisfy, and
// the one a truncation regression trips even when no single case pins it.
func TestDeriveTitleNeverExceedsMax(t *testing.T) {
	bodies := []string{
		strings.Repeat("word ", 200),                  // no period, forces truncateWords
		strings.Repeat("a very long sentence. ", 100), // many boundaries
		"x. " + strings.Repeat("y ", 300),             // short first sentence then noise
		strings.Repeat("日本", 400),                     // multibyte runes, no spaces
		"@type=semantic:lesson\n" + strings.Repeat("body ", 300),
	}
	for _, body := range bodies {
		got := DeriveTitle(body)
		if n := utf8.RuneCountInString(got); n > MaxTitle {
			t.Errorf("DeriveTitle returned %d runes (max %d): %q", n, MaxTitle, got)
		}
		if !utf8.ValidString(got) {
			t.Errorf("DeriveTitle returned invalid UTF-8: %q", got)
		}
	}
}

// TestStripHeader pins where the header line ends: a memory whose body
// discusses the header format must not have its prose read as metadata.
func TestStripHeader(t *testing.T) {
	tests := []struct {
		name string
		body string
		want string
	}{
		{"no header is trimmed", "  plain body  ", "plain body"},
		{"header stripped", "@type=lesson @salience=3\nlesson: the body.", "lesson: the body."},
		{"header only returns the header", "@type=lesson", "@type=lesson"},
		{"second-line at-sign is not a header", "plain first line\n@salience=9 mention", "plain first line\n@salience=9 mention"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := StripHeader(tt.body); got != tt.want {
				t.Errorf("StripHeader(%q) = %q, want %q", tt.body, got, tt.want)
			}
		})
	}
}

// TestNormalizeProvenance pins the optional field's stored form: blank input is
// nil so the JSON field is omitted, and non-blank input is trimmed.
func TestNormalizeProvenance(t *testing.T) {
	tests := []struct {
		name    string
		raw     string
		wantNil bool
		want    string
	}{
		{"empty is nil", "", true, ""},
		{"whitespace is nil", "   \n\t ", true, ""},
		{"plain text kept", "a skill", false, "a skill"},
		{"surrounding space trimmed", "  git log  ", false, "git log"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := NormalizeProvenance(tt.raw)
			if tt.wantNil {
				if got != nil {
					t.Errorf("NormalizeProvenance(%q) = %q, want nil", tt.raw, *got)
				}
				return
			}
			if got == nil || *got != tt.want {
				t.Errorf("NormalizeProvenance(%q) = %v, want %q", tt.raw, got, tt.want)
			}
		})
	}
}
